apiVersion: v1
kind: ConfigMap
metadata:
  name: idwo-config
  namespace: idwo
  labels:
    app.kubernetes.io/name: idwo
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"
  OPENAI_MODEL: "gpt-4-turbo-preview"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  CIRCUIT_BREAKER_TIMEOUT: "5000"
  CIRCUIT_BREAKER_THRESHOLD: "5"
  CIRCUIT_BREAKER_RESET_TIMEOUT: "30000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idwo-database-config
  namespace: idwo
  labels:
    app.kubernetes.io/name: idwo
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: "idwo"
  POSTGRES_USER: "postgres"
  REDIS_DB: "0"