apiVersion: v1
kind: Namespace
metadata:
  name: idwo
  labels:
    name: idwo
    app.kubernetes.io/name: idwo
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: idwo-quota
  namespace: idwo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    persistentvolumeclaims: "5"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: idwo-limits
  namespace: idwo
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container